In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install strsimpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting strsimpy
  Downloading strsimpy-0.2.1-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 2.2 MB/s
Installing collected packages: strsimpy
Successfully installed strsimpy-0.2.1

In [90]:
import pandas as pd
import numpy as np
import strsimpy
data_path = "/content/drive/MyDrive/Colab Notebooks/test_tichhop/All_data.csv"
data_df = pd.read_csv(data_path)
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7745 entries, 0 to 7744
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7745 non-null   object
 1   Hotel name         7745 non-null   object
 2   Url                7745 non-null   object
 3   Address            7745 non-null   object
 4   Stars              7745 non-null   float64
 5   Price              7745 non-null   int64
 6   Rating             7745 non-null   float64
 7   Number of reviews  7745 non-null   int64
 8   Reviews            7745 non-null   object
 9   Facilities         7745 non-null   object
 10  Description        6938 non-null   object
 11  Nearby places      7745 non-null   object
 12  Image              7745 non-null   object
dtypes: float64(2), int64(2), object(9)
memory usage: 786.7+ KB

In [91]:
levenshtein  = strsimpy.NormalizedLevenshtein()
def levenshtein_score(x,y):
    if (x=='unknown' or y =='unknown'):
        return 1
    return 1 - levenshtein.distance(x,y)

def difference_score(x,y):
    if (x=='unknown' or y =='unknown'):
        return 1
    return 1 if x==y else 0

In [92]:
def clust_filter(arr):
    flag = [False]*len(arr)
    cluster  = []
    for i in range(0,len(arr)-1):
        if (flag[i]==False):
            list_id = []
            for j in range(i + 1, len(arr)):
                if (flag[j]==False):
                    name = levenshtein_score(arr[i][0],arr[j][0])
                    cpu = difference_score(arr[i][2],arr[j][2])
                    ram = difference_score(arr[i][5],arr[j][5])
                    rom = difference_score(arr[i][6],arr[j][6])
                    color = difference_score(arr[i][10],arr[j][10])
                    score = 0.5 * name + 0.05 * cpu + 0.2 * ram + 0.2 * rom + 0.05 * color
                    if (score > 0.95):
                        flag[j] = True
                        list_id.append(j)
            arr[i].append(list_id)
            cluster.append(arr[i])
    return cluster

###import recordlinkage

In [ ]:
!pip install recordlinkage
!pip install Unidecode

In [13]:
import recordlinkage
import unidecode

In [93]:
data_df

,City,Hotel name,Url,Address,Stars,Price,Rating,Number of reviews,Reviews,Facilities,Description,Nearby places,Image
0,Hà Nội,Khách sạn HANZ Regal Hotel Hanoi,https://www.booking.com/hotel/vn/90-pham-huy-t...,"90 Pham Huy Thong, Quận Ba Đình, Hà Nội, Viê...",2.0,421890,7.8,86,"['“máy lạnh mát, wifi trong từng phòng nên mạn...","['Xe đưa đón sân bay', 'Wi-Fi miễn phí', 'P...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Hồ Ngọc Khánh', '0,3 km'), ('Trung tâm thươ...",['https://cf.bstatic.com/xdata/images/hotel/ma...
1,Hà Nội,Khách sạn La Nueva Boutique Hotel Hanoi & Spa,https://www.booking.com/hotel/vn/hanoi-eleganc...,"32 Lo Su Street, Quận Hoàn Kiếm, Hà Nội, Viê...",4.0,1316000,9.3,209,"['“Địa điểm tuyệt vời, đi một xíu là ra đến hồ...","['Xe đưa đón sân bay', 'Phòng không hút thu...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Nhà hát múa rối Thăng Long', '0,1 km'), ('Đ...",['https://cf.bstatic.com/xdata/images/hotel/ma...
2,Hà Nội,Khách sạn La Storia Ruby Hotel,https://www.booking.com/hotel/vn/hanoi-eleganc...,"3 Yen Thai Street, Quận Hoàn Kiếm, Hà Nội, V...",3.0,625000,9.6,217,['“- vị trí gần hồ gươm rất tiện cho việc đi b...,"['Xe đưa đón sân bay', 'Phòng không hút thu...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Quảng Trường Đông Kinh Nghĩa Thục', '0,4 km...",['https://cf.bstatic.com/xdata/images/hotel/ma...
3,Hà Nội,Khách sạn LeaH Silk Hotel,https://www.booking.com/hotel/vn/leah-silk.vi....,"41- 43 Hàng Bông, Hoàn Kiếm , Hà Nội, Quận Hoà...",4.0,1800000,9.1,72,"['“Mình ở phòng có cửa thông với phòng khác, v...","['1 hồ bơi', 'Xe đưa đón sân bay', 'Phòng kh...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Nhà thờ Thánh Joseph', '0,3 km'), ('Quảng T...",['https://cf.bstatic.com/xdata/images/hotel/ma...
4,Hà Nội,Khách sạn Babylon Premium Hotel & Spa,https://www.booking.com/hotel/vn/babylon-premi...,"05-07 Hàng Hòm, Quận Hoàn Kiếm, Hà Nội, Việ...",4.0,1262250,9.4,627,['“Phòng rất rộng và sạch.\nVị trí ngay giữa k...,"['Xe đưa đón sân bay', 'Phòng không hút thu...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Quảng Trường Đông Kinh Nghĩa Thục', '0,3 km...",['https://cf.bstatic.com/xdata/images/hotel/ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7740,Hạ Long,Khách sạn The Twin,https://mytour.vn/khach-san/44177-khach-san-th...,"Tt 31-32 , Đường Hạ Long - Sun Premier Village...",4.0,1684766,8.0,1,['Giải quyết linh động tinh huống cho khách kh...,"['Đưa/đón khách sân bay', 'Lễ tân 24h', 'Giữ h...","['Tọa lạc ở thành phố Hạ Long, cách cáp treo N...","[('Nhà hàng Bayview', '369 m'), ('Nhà Hàng Phư...",['https://img.tripi.vn/cdn-cgi/image/width=124...
7741,Hạ Long,Khách sạn Sea Star,https://mytour.vn/khach-san/39745-khach-san-se...,"Bt 08 - Khu Villa Sao Biển, Phan Chu Trinh, Th...",3.0,665456,8.2,9,['Tạm được\nĐi gia đình đúng dịp dịch nên cả n...,"['American Express', 'Đưa/đón khách sân bay', ...","['Được nâng cấp vào năm , Khách sạn Sea Stars ...","[('Nhà hàng Cua Vàng', '59 m'), ('1900 Coff...",['https://img.tripi.vn/cdn-cgi/image/width=124...
7742,Hạ Long,Khách Sạn Dragon Hạ Long,https://mytour.vn/khach-san/53773-khach-san-dr...,"8 , Lộc Vừng 2 , Khu Premier Village , Đườn...",3.0,897838,8.4,0,[],"['Bãi đỗ xe', 'Cho thuê xe máy', 'Giữ hành lý'...",['Khách Sạn Dragon Hạ Long là nơi cung cấp dị...,[],['https://img.tripi.vn/cdn-cgi/image/width=124...
7743,Hạ Long,Khách Sạn Sunshine,https://mytour.vn/khach-san/49166-khach-san-su...,"56a Tuệ Tĩnh, Khu Đô Thị Hồng Vận, Đường Tuệ T...",2.0,508093,7.0,0,[],"['Lễ tân 24h', 'Giữ hành lý', 'Bán tour', 'Int...",['Sunshine Hotel in Móng Cái has 2-star accomm...,"[('Don Chicken Vincom Móng Cái', '930 m'), ('N...",['https://img.tripi.vn/cdn-cgi/image/width=124...
7744,Hạ Long,Khách sạn Galaxy Hạ Long,https://mytour.vn/khach-san/39775-khach-san-ga...,"15, Tiên Ông, Phường Bãi Cháy, Thành Phố Hạ Lo...",4.0,753251,9.4,5,['Galaxy Hotel Hạ Long\nMình đặt 1 phòng 3 giư...,"['Đưa/đón khách sân bay', 'Phòng gym', 'Giữ hà...",['Được UNESCO công nhận là di sản thiên nhiên ...,"[('Nhà Hàng Lâm Hải', '131 m'), ('Mixue Bãi Ch...",['https://img.tripi.vn/cdn-cgi/image/width=840...

###Hotel-name

In [94]:
#Bước 1: Chuyển tên KS về dạng chữ thường
data_df['new_name'] = data_df['Hotel name'].str.lower()
data_df['new_name']

0                    khách sạn hanz regal hotel hanoi
1       khách sạn la nueva boutique hotel hanoi & spa
2                      khách sạn la storia ruby hotel
3                           khách sạn leah silk hotel
4               khách sạn babylon premium hotel & spa
                            ...
7740                               khách sạn the twin
7741                               khách sạn sea star
7742                      khách sạn dragon hạ long
7743                               khách sạn sunshine
7744                         khách sạn galaxy hạ long
Name: new_name, Length: 7745, dtype: object

In [95]:
#Bước 2: Loại bỏ những substring thông dụng: khách sạn, căn hộ,...
subnames = ["căn hộ", "apartment", 
            "khách sạn", "hotel", "hostel", "nhà khách", "nhà thuyền"
            "khu", "nghỉ dưỡng", "nghỉ mát", "resort", "spa",
            "nhà", "nhà dân dịch vụ", "home", "house", "homestay", "serviced homestay",
            "biệt thự", "villa", 
            "du thuyền", "cruise", 
            "gần", "sang trọng", "near", "luxury", "mới", 
            "bungalow", "restaurant", "residences", "studio", "bar", 
            "và", "and", "&"
            ]
data_df['new_name'].replace(subnames,'', inplace=True, regex=True)
data_df['new_name']

0                 hanz regal  hanoi
1        la nueva boutique  hanoi
2                   la storia ruby
3                        leah silk
4                babylon premium
                   ...
7740                       the twin
7741                       sea star
7742    khách sạn dragon hạ long
7743                       sunshine
7744                 galaxy hạ long
Name: new_name, Length: 7745, dtype: object

In [96]:
#Bước 3: Bỏ dấu
data_df['new_name']=[unidecode.unidecode(y) for y in data_df['new_name']]
data_df['new_name']

0                 hanz regal  hanoi
1        la nueva boutique  hanoi
2                   la storia ruby
3                        leah silk
4                babylon premium
                   ...
7740                       the twin
7741                       sea star
7742       khach san dragon ha long
7743                       sunshine
7744                 galaxy ha long
Name: new_name, Length: 7745, dtype: object

In [97]:
#Bước 4: Với những tên KS có 2 phần tiếng anh, tiếng việt --> lấy 1 phần
data_df['new_name'] = [y.partition('(')[0] for y in data_df['new_name']]
data_df['new_name']

0                 hanz regal  hanoi
1        la nueva boutique  hanoi
2                   la storia ruby
3                        leah silk
4                babylon premium
                   ...
7740                       the twin
7741                       sea star
7742       khach san dragon ha long
7743                       sunshine
7744                 galaxy ha long
Name: new_name, Length: 7745, dtype: object

In [98]:
#Bước 5: Loại bỏ khoảng cách giữa các từ
data_df['new_name'].replace(' ','', inplace=True, regex=True)
data_df['new_name']

0             hanzregalhanoi
1       lanuevaboutiquehanoi
2               lastoriaruby
3                   leahsilk
4             babylonpremium
                ...
7740                 thetwin
7741                 seastar
7742    khachsandragonhalong
7743                sunshine
7744            galaxyhalong
Name: new_name, Length: 7745, dtype: object

###Address

In [99]:
#Bước 1: Chuyển về dạng chữ thường
#Bước 1: Chuyển tên KS về dạng chữ thường
data_df['new_add'] = data_df['Address'].str.lower()
data_df['new_add']

0       90 pham huy thong, quận ba đình, hà nội, viê...
1       32 lo su street, quận hoàn kiếm, hà nội, viê...
2       3 yen thai street, quận hoàn kiếm, hà nội, v...
3       41- 43 hàng bông, hoàn kiếm , hà nội, quận hoà...
4       05-07 hàng hòm, quận hoàn kiếm, hà nội, việ...
                              ...
7740    tt 31-32 , đường hạ long - sun premier village...
7741    bt 08 - khu villa sao biển, phan chu trinh, th...
7742    8 , lộc vừng 2 , khu premier village , đườn...
7743    56a tuệ tĩnh, khu đô thị hồng vận, đường tuệ t...
7744    15, tiên ông, phường bãi cháy, thành phố hạ lo...
Name: new_add, Length: 7745, dtype: object

In [100]:
#Kiểm tra xem có bản ghi nào chứa "vn" hay không?
m1_df = data_df[data_df['new_add'].str.contains('vn')]
m1_df

,City,Hotel name,Url,Address,Stars,Price,Rating,Number of reviews,Reviews,Facilities,Description,Nearby places,Image,new_name,new_add
3837,Nha Trang,Căn hộ Căn hộ cao cấp,https://www.booking.com/hotel/vn/can-ho-cao-ca...,"Căn hộ VNC - CT3 Phước Hải, Nha Trang, Việt Nam",0.0,864000,0.0,0,[],[],Căn hộ cao cấp is a property with a private po...,"[('Bến xe Buýt Liên tỉnh', '1,2 km'), ('Nha Th...",['https://cf.bstatic.com/xdata/images/hotel/ma...,caocap,"căn hộ vnc - ct3 phước hải, nha trang, việt nam"
3908,Phú Quốc,Nhà nghỉ B&B Sunny Venice Grand World Phu Quoc...,https://www.booking.com/hotel/vn/sunny-venice-...,"Vinpearl VN-22 Grand World Phú Quốc, Ganh Dau,...",3.0,624000,8.4,11,"['“Các bạn nv rất nhiệt tình, ra vào chào khác...","['Dịch vụ đưa đón sân bay (miễn phí)', 'Chỗ đ...","Nằm cách Bãi biển Vũng Bầu 2,1 km, Sunny Venic...","[('Sòng bạc Corona Casino', '0,7 km'), ('Công ...",['https://cf.bstatic.com/xdata/images/hotel/ma...,nghibbsunnyvenicegrworldphuquocunitedcenter,"vinpearl vn-22 grand world phú quốc, ganh dau,..."
3923,Phú Quốc,Nhà khách Venice Cafe and Homestay,https://www.booking.com/hotel/vn/venice-cafe-a...,"Gành Dầu - Cửa Cạn VN-10 Grand World, Ganh Dau...",3.0,700000,7.9,7,"['“The location is great, on the balcony, you ...","['Xe đưa đón sân bay', 'Phòng không hút thu...",Chỗ nghỉ này cách bãi biển 12 phút đi bộ. Tọa ...,"[('Sòng bạc Corona Casino', '0,6 km'), ('Công ...",['https://cf.bstatic.com/xdata/images/hotel/ma...,venicecafestay,"gành dầu - cửa cạn vn-10 grand world, ganh dau..."
3955,Phú Quốc,Khách sạn HANZ Premium Power Hotel Grand World...,https://www.booking.com/hotel/vn/hanz-power-mi...,"VN44 Grand World, Bãi Dài, Gành Dầu, Phú Quốc....",0.0,874650,8.2,8,"['“nam tai trung tam grandworld rat dep, di la...","['Dịch vụ đưa đón sân bay (miễn phí)', 'Phòng...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Sòng bạc Corona Casino', '0,8 km'), ('Công ...",['https://cf.bstatic.com/xdata/images/hotel/ma...,hanzpremiumpowergrworldphuquoc,"vn44 grand world, bãi dài, gành dầu, phú quốc...."
4143,Phú Quốc,Khách sạn Mới Fern Forest Homestay,https://www.booking.com/hotel/vn/fern-forest-h...,"Grand World, Gành Dầu, Phú Quốc VN - 03, Ganh ...",0.0,600000,0.0,0,[],"['Phòng không hút thuốc', 'Giáp biển', 'Chô...","Situated in Phu Quoc, within 2.3 km of Vung Ba...","[('Sòng bạc Corona Casino', '0,8 km'), ('Công ...",['https://cf.bstatic.com/xdata/images/hotel/ma...,fernforeststay,"grand world, gành dầu, phú quốc vn - 03, ganh ..."
5464,Hà Nội,Khách sạn Ancient Lane (Ancient Lane Hotel),https://www.agoda.com/vi-vn/ancient-lane-hotel...,"Số 2 đường Tam Thương, Phường Hàng Gai, Quận H...",35.0,662338,9.0,1236,['địa điểm thì do nằm trong hẻm vì Hà nội đặt ...,"['Cách phương tiện công cộng 950 m', 'Nằm ở tr...",NaN,"['Việt Nam Bảo tàng Lịch sử quân sự - 800 m', ...",https://pix6.agoda.net/hotelImages/5100415/-1/...,ancientlane,"số 2 đường tam thương, phường hàng gai, quận h..."

In [101]:
#Bước 2: Loại bỏ mã vùng/mã tỉnh 
data_df['new_add'] = [y.partition(', việt nam')[0] for y in data_df['new_add']]
data_df['new_add']

0       90 pham huy thong, quận ba đình, hà nội, viê...
1       32 lo su street, quận hoàn kiếm, hà nội, viê...
2       3 yen thai street, quận hoàn kiếm, hà nội, v...
3       41- 43 hàng bông, hoàn kiếm , hà nội, quận hoà...
4       05-07 hàng hòm, quận hoàn kiếm, hà nội, việ...
                              ...
7740    tt 31-32 , đường hạ long - sun premier village...
7741    bt 08 - khu villa sao biển, phan chu trinh, th...
7742    8 , lộc vừng 2 , khu premier village , đườn...
7743    56a tuệ tĩnh, khu đô thị hồng vận, đường tuệ t...
7744    15, tiên ông, phường bãi cháy, thành phố hạ lo...
Name: new_add, Length: 7745, dtype: object

In [102]:
#Bước 3: Loại bỏ các substring thông dụng
subadds = ["xóm", "quận", "thị xã", "ngõ", "số", "tòa", "thành phố", "phố cổ", "phố",  
           "đường", "phường", "cư xá", "cảng", "hẻm", "khu", "đô thị", "nhà",
           "ngách", "phòng", "căn", "tầng", "tỉnh", "tổ", "ap", "ấp", "lô", "bãi",
           "xã", "huyện", "du lịch", "di tích", "đại lộ", "đảo", "và", "tel 02633.608084",
           "trung tâm", "đối diện", "phía", "sau", "trước", "siêu thị", "vn", "quan",
           "no", "no.", "nos", "island", "alley", "lane", "street", "ward", "district",
           "group", "province", "block", "beach", "city", "basilica", "market", "lake",
           "area", "unit", "gate", "port", "wharft", "near by", "building", "zone",
           "tp", "str", "st", "dist", "pro", "bis", "kđt", "hcmc", "hcm", 
           "hà nội", "hồ chí minh", "đà lạt", "đà nẵng", "nha trang", "vũng tàu", 
           "phú quốc", "quảng ninh", "hạ long", "ha long", "ha noi", "ho chi minh",
           "da lat", "da nang", "vung tau", "phu quoc", "quang ninh", "viet nam", "vietnam", 
           ","
            ]

data_df['new_add'].replace(subadds,'', inplace=True, regex=True)
data_df['new_add']

0           90 pham huy thong  ba đình hà nội việt nam
1                 32 lo su   hoàn kiếm hà nội việt nam
2               3 yen thai   hoàn kiếm hà nội việt nam
3       41- 43 hàng bông hoàn kiếm    hoàn kiếm hà nô...
4            05-07 hàng hòm  hoàn kiếm hà nội việt nam
                              ...
7740         tt 31-32    - sun premier village halong
7741            bt 08 -  villa sao biển phan chu trinh
7742    8  ̣c vừng 2   premier village  đường hạ lo...
7743         56a tuệ tĩnh   hồng vận  tuệ tĩnh  móng cái
7744                                15 tiên ông   cháy
Name: new_add, Length: 7745, dtype: object

In [103]:
# #Bước 4: Bỏ dấu
data_df['new_add']=[unidecode.unidecode(y) for y in data_df['new_add']]
data_df['new_add']

0              90 pham huy thong  ba dinh ha noi viet nam
1                    32 lo su   hoan kiem ha noi viet nam
2                  3 yen thai   hoan kiem ha noi viet nam
3       41- 43 hang bong hoan kiem    hoan kiem ha noi...
4               05-07 hang hom  hoan kiem ha noi viet nam
                              ...
7740         tt 31-32    - sun premier village halong
7741            bt 08 -  villa sao bien phan chu trinh
7742     8  c vung 2   premier village  duong ha long
7743         56a tue tinh   hong van  tue tinh  mong cai
7744                                15 tien ong   chay
Name: new_add, Length: 7745, dtype: object

In [104]:
#Bước 5: Loại bỏ khoảng cách giữa các từ
data_df['new_add'].replace(' ','', inplace=True, regex=True)
data_df['new_add']

0                90phamhuythongbadinhhanoivietnam
1                      32losuhoankiemhanoivietnam
2                    3yenthaihoankiemhanoivietnam
3       41-43hangbonghoankiemhoankiemhanoivietnam
4                05-07hanghomhoankiemhanoivietnam
                          ...
7740              tt31-32-sunpremiervillagehalong
7741                bt08-villasaobienphanchutrinh
7742             8cvung2premiervillageduonghalong
7743              56atuetinhhongvantuetinhmongcai
7744                                15tienongchay
Name: new_add, Length: 7745, dtype: object

###Compare

In [105]:
compare = recordlinkage.Compare()

# initialise similarity measurement algorithms
compare.string('new_add', 'new_add', method='jarowinkler', threshold=0.85, label='Address')
compare.string('new_name', 'new_name', method='levenshtein', threshold=0.85, label='Hotel_name')
compare.string('City', 'City', method='jarowinkler', threshold=0.85, label='City')

In [106]:
indexer = recordlinkage.Index()
indexer.block(left_on='City')

In [107]:
eb_dup=indexer.index(data_df)
eb_ft=compare.compute(eb_dup,data_df)

In [108]:
eb_matches = eb_ft[eb_ft.sum(axis=1) >=2.5].reset_index()
eb_matches

     level_0  level_1  Address  Hotel_name  City
0        296      204      1.0         1.0   1.0
1        334      264      1.0         1.0   1.0
2        693      138      1.0         1.0   1.0
3        756      712      1.0         1.0   1.0
4        794      455      1.0         1.0   1.0
..       ...      ...      ...         ...   ...
780     6931     5399      1.0         1.0   1.0
781     6934     5749      1.0         1.0   1.0
782     6937     5396      1.0         1.0   1.0
783     7727     6677      1.0         1.0   1.0
784     7737     6674      1.0         1.0   1.0

[785 rows x 5 columns]

In [109]:
data_df.loc[2478]

City                                                            Đà Lạt
Hotel name                                Khách sạn Lacami Dalat Hotel
Url                  https://www.booking.com/hotel/vn/lacami-dalat....
Address              36/6 Lê Văn Tám, Phường 2, thành phố Đà Lạt, L...
Stars                                                              2.0
Price                                                           460000
Rating                                                             7.8
Number of reviews                                                   11
Reviews                                                             []
Facilities           ['Xe đưa đón sân bay', 'Phòng không hút thu...
Description          Tọa lạc tại thành phố Đà Lạt, cách Công viên Y...
Nearby places        [('Chùa Tàu Thiên Vương Cổ Sát', '0,4 km'), ('...
Image                ['https://cf.bstatic.com/xdata/images/hotel/ma...
new_name                                                   lacamidalat
new_add                                    36/6levantam2lamdongvietnam
Name: 2478, dtype: object

In [110]:
data_df.loc[6062]

City                                                            Đà Lạt
Hotel name                                          Lacami Dalat Hotel
Url                  https://www.traveloka.com/vi-vn/hotel/vietnam/...
Address              36/6 Lê Văn Tám, phường 10, Đà Lạt, Tỉnh Lâm Đ...
Stars                                                              2.0
Price                                                           400000
Rating                                                             8.6
Number of reviews                                                   62
Reviews              ['Trải nghiệm rất là tồi tệ. - Dầu gội không c...
Facilities             ['Nhà hàng', 'Chỗ đậu xe', 'Thang máy', 'WiFi']
Description          Giờ nhận và trả phòng\r\nGiờ nhận phòng: 14:00...
Nearby places        [('Big C Dalat', '1.21 km'), ('Hồ Xuân Hương',...
Image                ['https://ik.imagekit.io/tvlk/apr-asset/dgXfoy...
new_name                                                   lacamidalat
new_add                                          36/6levantam10lamdong
Name: 6062, dtype: object

In [111]:
len(eb_dup)

3204072

In [112]:
eb_ft.sum(axis=1).value_counts().sort_index(ascending=False)

3.0        785
2.0      27635
1.0    3175652
dtype: int64

In [113]:
eb_matches = eb_ft[eb_ft['Hotel_name'].values*6+ eb_ft['Address'].values*3+eb_ft['City'].values >=9.2 ].reset_index()

In [114]:
match=eb_matches['level_0'].unique()
num=len(match)
tick=[1]*max(eb_matches['level_0'].max(),eb_matches['level_1'].max())+[1]
ls=[]
for i in match:
    #if tick[i]:
        
        a=set()
        
        b=set()
        b.add(i)
        while b:
            val=b.pop()
            if tick[val]:
                a.add(val)
                tick[val]=0
                x=eb_matches.loc[eb_matches['level_0']==val,'level_1'].to_list()
                x=x+eb_matches.loc[eb_matches['level_1']==val,'level_0'].to_list()
                for j in x:
                    if j:
                        b.add(j)
                        a.add(j)
        if a:
            ls.append(a)

In [115]:
for i in ls:
    print(i)

{296, 204}
{264, 334}
{138, 693}
{712, 756}
{794, 455}
{816, 743}
{914, 837, 783}
{602, 892}
{882, 907, 893}
{881, 898, 926, 903}
{901, 70}
{736, 932}
{966, 943}
{843, 967}
{959, 983}
{987, 852, 989}
{216, 304, 988}
{1086, 1063}
{1265, 1178}
{1753, 1638, 1326, 1327}
{1412, 1109}
{1200, 1462}
{1489, 1374}
{1181, 1783}
{1176, 1881, 1796}
{1864, 1261}
{1755, 1895}
{1678, 1918}
{1218, 1919}
{1945, 1683}
{2520, 2043}
{2525, 2511}
{2547, 2255}
{5606, 2327}
{2283, 5614}
{2554, 7189, 5615}
{5618, 2269, 6118}
{6034, 2236, 5621}
{5625, 6055, 2343}
{2104, 5628}
{2144, 6019, 5630}
{5632, 2233}
{5640, 7234, 2147, 6142}
{6138, 2178, 5643}
{2041, 5646}
{5648, 2219, 7240}
{5649, 2291}
{5956, 2431}
{2207, 5959}
{2369, 5963, 5612, 7181}
{2185, 7284, 5966}
{2004, 5974}
{5976, 2290, 7200}
{5977, 2170}
{2313, 5978, 7247}
{2308, 5989, 7228}
{5992, 7274, 1996}
{5993, 2498, 7285}
{1985, 7195, 5996}
{1977, 5997}
{6002, 2206}
{6003, 2220}
{6004, 2485}
{2032, 6006}
{6009, 2443}
{2412, 6030}
{6043, 2142}
{6052, 2309}
{7288, 2478, 6062}
{6066, 1983}
{2544, 6069}
{1997, 6070}
{2121, 6076}
{2281, 7253, 6077}
{2155, 6084}
{5617, 6087}
{2161, 6091}
{7259, 6093, 2278}
{5626, 6111}
{6114, 2067}
{6116, 2445}
{7227, 2468, 6126}
{2447, 6127}
{6128, 6094}
{6130, 2102}
{2317, 6134}
{2423, 6135}
{2360, 6145}
{2241, 6146}
{6149, 2246}
{2499, 6150}
{2504, 6161, 7265}
{6168, 2217}
{2088, 6169}
{2409, 6181}
{2480, 6221}
{6241, 2482}
{2552, 6251}
{2562, 6255}
{6266, 2378}
{2257, 6290}
{2297, 6295}
{2432, 6297}
{5603, 7182}
{2448, 7183}
{7184, 5613}
{7185, 5986}
{7192, 6018}
{2272, 7196}
{7202, 2335}
{7203, 5972}
{6016, 7204}
{7205, 6078}
{5645, 7206}
{2266, 7207}
{7208, 5969}
{7210, 1975}
{6298, 7211}
{5964, 7214}
{6064, 7215}
{7217, 2556}
{7218, 2118}
{2450, 7220}
{7221, 6254}
{7225, 2127}
{7229, 6198}
{6112, 7237}
{6273, 7243}
{7244, 2221}
{6060, 7245}
{6155, 7252}
{7257, 6022}
{7260, 6180}
{7264, 2332}
{7272, 6026, 2149}
{2109, 7278}
{7283, 2311}
{5634, 7291}
{2804, 2630}
{3185, 3090, 2987, 2628}
{2640, 3250, 3060}
{3155, 3076}
{7365, 5492, 2999, 5496, 3198}
{3348, 3334}
{3133, 5487}
{5488, 2944}
{6306, 5491, 3039}
{2968, 6315, 5494, 7319}
{3065, 5499}
{5505, 2873}
{2827, 7300, 5511}
{5512, 2578}
{5516, 3015}
{2710, 5518}
{5520, 7337, 2852}
{5521, 2851}
{7441, 2890, 5526}
{3058, 5534}
{5536, 7343, 2775}
{5537, 2959}
{5540, 2846}
{2659, 7428, 5542}
{2904, 5543}
{5544, 3195, 7372}
{2705, 5546}
{5548, 2901}
{3097, 5550}
{5552, 2586, 7384}
{7417, 5555, 3100}
{2806, 6309, 5558}
{5560, 6323, 2716}
{5564, 3191}
{3001, 5566, 7438}
{5568, 3069}
{2746, 5570}
{2811, 5573}
{3006, 5575}
{2699, 5591}
{5593, 5517}
{6338, 5594, 2566}
{5598, 2991}
{6300, 5527}
{3005, 6302}
{6304, 3012}
{6307, 2805}
{2731, 6311}
{6313, 3212, 7294, 3135}
{2779, 6316}
{7356, 6317, 2958}
{5553, 6318}
{5559, 6319}
{6324, 2949}
{6331, 2975}
{3002, 6332}
{3242, 6340}
{5581, 6342}
{3059, 6349}
{2919, 6351}
{6354, 2666}
{2671, 6359}
{3184, 6365}
{2764, 6366}
{6368, 3064}
{6369, 2853}
{6377, 2834, 7348}
{7297, 2985}
{2960, 7298}
{3041, 7302}
{7304, 3055}
{7306, 5501}
{7308, 3054}
{3034, 7310}
{2859, 7311}
{3077, 7318}
{7321, 3258}
{2940, 7326}
{7329, 2631}
{3243, 7333}
{2736, 7335}
{7336, 3303}
{7338, 2844}
{7339, 2990}
{5489, 7340}
{3066, 6356, 7342}
{7345, 3270}
{7346, 6326, 2822}
{7352, 6322}
{3321, 7354}
{7357, 3150}
{7360, 5569}
{2828, 7366}
{7368, 2684}
{2600, 7371}
{6312, 7373}
{7380, 3127}
{3189, 7381}
{2982, 7383}
{5497, 7387, 3045}
{7389, 2718}
{7392, 2971}
{7393, 2847}
{7395, 3172}
{7397, 2574}
{6375, 7399}
{7403, 6350}
{7405, 5565}
{5524, 7406}
{7408, 2970}
{6321, 7410}
{7411, 2821}
{2570, 7414}
{2663, 7415}
{2885, 7422}
{2784, 6361, 7423}
{7426, 2606}
{7427, 3230}
{7429, 3158}
{2603, 7431}
{7432, 6348}
{7433, 3085}
{3096, 7436}
{3079, 7439}
{2641, 7445}
{2842, 7446}
{7448, 2717}
{5561, 7450}
{7451, 3035}
{2917, 7454}
{7457, 2902}
{3393, 3389}
{3457, 3773, 3487}
{3553, 3471}
{3531, 3630}
{3575, 3647}
{3656, 3616, 4861, 7566}
{3706, 3691, 3797}
{3723, 3527}
{3670, 3726}
{3729, 3738}
{3618, 3749}
{3778, 3810, 3786, 3821, 3694, 3792, 3766, 3775}
{3802, 3788, 3751}
{3808, 3397}
{3668, 3813}
{3695, 3823}
{3697, 3829}
{3830, 3831}
{3836, 3381}
{3843, 3765}
{3528, 4850}
{4851, 3549}
{6386, 3551, 7474, 4855}
{4856, 3714, 7480}
{4857, 3579, 7473}
{3552, 4858}
{3445, 4862}
{4864, 3562, 7491}
{4865, 3598}
{4866, 3574, 7551}
{4872, 3576}
{3648, 4873}
{3475, 4876, 7558}
{4880, 3573, 7502}
{3512, 4886}
{4888, 3362}
{3498, 4892}
{4893, 3485}
{4896, 3493}
{4897, 3761, 7537}
{4898, 3563, 7579}
{3443, 4901}
{3613, 4903}
{7568, 4907, 3495}
{4912, 3456}
{4917, 3454}
{3736, 4932}
{4933, 3734}
{4939, 3492, 7547}
{3366, 7574, 4942}
{3604, 6382}
{6385, 7471, 3623}
{3395, 6387}
{3506, 6389}
{6394, 4900}
{6395, 3476}
{6397, 3477}
{3558, 6398}
{7464, 4870}
{7465, 3674}
{7466, 3599}
{3568, 7469}
{4875, 7475}
{4849, 7477}
{7489, 3610}
{7490, 3378}
{7499, 4924}
{3619, 7503}
{7506, 3523}
{7508, 4950}
{3676, 7509}
{3824, 7510}
{7520, 3581}
{7532, 3372}
{7539, 3460}
{4916, 7550}
{7557, 6391}
{7569, 3399}
{3621, 7575}
{3874, 7646, 7601, 7604, 4023, 4126}
{4172, 4189}
{6400, 3953}
{3961, 6402}
{4113, 6405}
{4064, 6406}
{4117, 6407}
{6410, 3957}
{3968, 6414}
{6416, 4148}
{4016, 6417}
{3969, 6419}
{3983, 6423}
{6426, 3998}
{4118, 6431}
{6435, 4027}
{6449, 4066}
{6473, 4076}
{4163, 6475}
{3904, 6482}
{3920, 6489}
{3977, 6490}
{4152, 6491}
{4050, 6501}
{6502, 4159}
{6507, 4069}
{4072, 6508}
{4200, 6516}
{7585, 4110}
{7592, 4203}
{7593, 6443}
{7595, 4083}
{3901, 7605}
{4010, 7620}
{3948, 7621}
{6418, 7622}
{7624, 6459}
{4024, 7627}
{4099, 7630}
{7641, 3940}
{7643, 6445}
{4178, 7655}
{7657, 4026}
{7660, 6469}
{4058, 7661}
{3987, 7663}
{4232, 4233, 4229}
{4217, 4234}
{4339, 4303}
{4512, 4212, 4461}
{4468, 4494}
{4610, 4515, 4583, 4537, 4222}
{4547, 4590}
{4616, 4546}
{4625, 4485}
{4611, 4631}
{4698, 4719}
{6610, 6522, 5005, 7694}
{4998, 6527}
{6578, 6525}
{6601, 6559}
{6633, 5017}
{6545, 7684}
{5013, 7686}
{6536, 7695}
{7697, 6615}
{7704, 6531}
{7709, 6623}
{7713, 6643}
{7716, 6637}
{7720, 4995}
{5080, 5762, 7095}
{5152, 5763}
{5131, 5764}
{5202, 5771}
{5096, 7134, 5775}
{5072, 5777, 7155}
{5113, 7076, 5780}
{5794, 5149}
{5075, 5804, 6982}
{5135, 5807}
{5808, 5129}
{5099, 6966, 5815}
{5123, 5823}
{5824, 5192}
{5825, 5124}
{5062, 5831}
{5832, 5150}
{5106, 5843, 6981}
{5194, 5844}
{5849, 5238}
{5220, 5855}
{5857, 5067}
{5144, 5860}
{5148, 5885}
{5889, 5132}
{6992, 5891, 5076}
{5104, 5901}
{5904, 5854}
{5906, 7042, 5167}
{5912, 5200}
{5913, 5251}
{5916, 5215}
{5173, 5933}
{5206, 5942}
{6953, 5069}
{5058, 6954}
{6955, 5052}
{5089, 6956}
{6958, 5047}
{6962, 5119}
{5116, 6965}
{6968, 5065}
{6969, 5063}
{6970, 5068}
{5056, 6971}
{5112, 6972}
{5070, 6974}
{5077, 6975}
{6977, 5078}
{6978, 5051}
{5050, 6980}
{6986, 5156}
{5947, 6990}
{5866, 6991}
{6994, 5918}
{5802, 6997}
{7011, 5894}
{7017, 5793}
{5161, 7020}
{5816, 7029}
{5097, 7030}
{7032, 5091}
{7035, 5878}
{5822, 7038}
{7048, 7049}
{5053, 7055}
{5209, 7066}
{5898, 7068}
{5107, 7069}
{5784, 7070}
{7072, 5226}
{5840, 7074}
{5884, 7078}
{5770, 7079}
{7090, 5126}
{7091, 5830}
{5136, 7093}
{7098, 5103}
{5853, 7103}
{7106, 5927}
{7107, 5774}
{7108, 5814}
{5768, 7110}
{5876, 7111}
{7113, 5817}
{5810, 7114}
{5087, 7119}
{7082, 7123, 7166}
{7129, 5246}
{5915, 7135}
{7138, 5806}
{5863, 7143}
{5800, 7145}
{5837, 7149}
{5259, 7151}
{7152, 5195}
{7161, 5133}
{7165, 5862}
{5211, 7167}
{5873, 7171}
{7172, 5110}
{5313, 5652, 6871}
{5298, 5658, 6738}
{5665, 5322, 6821}
{5402, 5676}
{5720, 5401}
{5725, 5423}
{5374, 5734}
{5422, 5742}
{5335, 5743}
{5753, 6731, 5388}
{5304, 6715}
{6716, 5295}
{5746, 6718}
{6723, 5292}
{5306, 6725}
{6728, 5755}
{6729, 5286}
{5329, 6733}
{6746, 5378}
{5369, 6750}
{6752, 5662}
{6761, 5737}
{5370, 6775}
{6776, 5450}
{6779, 5318}
{5704, 6790}
{5433, 6791}
{6800, 5332}
{6804, 5391}
{6805, 5439}
{6809, 5677}
{6824, 5685}
{6825, 5419}
{6826, 5357}
{5669, 6829}
{6836, 5445}
{6864, 6842}
{5425, 6874}
{6875, 5420}
{6876, 5663}
{6885, 5670}
{5324, 6894}
{6904, 5338}
{5381, 6911}
{6916, 5701}
{6920, 5698}
{5317, 6927}
{6931, 5399}
{5749, 6934}
{6937, 5396}
{6677, 7727}
{7737, 6674}

In [125]:
for iter in ls:
    min_prince = 999999999999999999999999999999
    min_id = -1
    for id in iter:
        if data_df.loc[id]["Price"] < min_prince:
            min_id = id
            min_prince = data_df.loc[id]["Price"]
    for id in iter:
        if id != min_id:
            data_df = data_df.drop([id])
            print(id)

204
334
693
756
455
743
914
837
892
907
893
898
926
903
70
932
966
967
959
852
989
304
988
1086
1178
1753
1638
1326
1412
1462
1489
1181
1176
1881
1261
1895
1678
1919
1945
2043
2511
2547
2327
2283
2554
7189
2269
6118
6034
2236
6055
2343
2104
2144
6019
2233
7234
2147
6142
6138
2178
2041
5648
2219
2291
2431
2207
2369
5963
7181
2185
7284
5974
5976
2290
5977
2313
5978
2308
7228
5992
1996
5993
2498
1985
5996
5997
2206
6003
2485
6006
6009
2412
2142
2309
7288
2478
6066
6069
6070
6076
2281
6077
6084
6087
6091
6093
2278
6111
6114
6116
2468
6126
6127
6128
2102
6134
6135
6145
6146
2246
6150
2504
6161
6168
2088
6181
2480
2482
6251
6255
6266
6290
6295
2432
7182
2448
7184
5986
6018
2272
2335
5972
7204
6078
7206
2266
5969
1975
6298
5964
6064
7217
2118
2450
6254
2127
6198
6112
6273
2221
6060
6155
6022
6180
2332
6026
2149
2109
2311
5634
2804
3185
2987
2628
3250
3060
3076
7365
2999
5496
3198
3334
3133
2944
6306
3039
2968
6315
7319
3065
2873
2827
7300
2578
3015
2710
7337
2852
5521
2890
5526
3058
7343
2775
2959
2846
2659
7428
2904
3195
7372
2705
2901
3097
5552
2586
7417
3100
2806
5558
6323
2716
3191
3001
7438
3069
2746
2811
3006
2699
5517
6338
5594
2991
6300
6302
3012
6307
6311
6313
3212
3135
6316
6317
2958
6318
6319
2949
2975
3002
6340
6342
3059
6351
6354
6359
6365
6366
6368
2853
6377
2834
2985
2960
3041
3055
5501
3054
3034
7311
3077
3258
2940
2631
3243
2736
3303
2844
2990
5489
6356
7342
3270
7346
6326
6322
3321
3150
7360
2828
2684
7371
6312
3127
3189
2982
7387
3045
7389
2971
2847
3172
7397
6375
6350
7405
5524
2970
6321
2821
2570
2663
7422
2784
6361
2606
3230
3158
2603
6348
3085
3096
3079
7445
2842
2717
7450
3035
2917
2902
3393
3773
3487
3553
3531
3575
3656
3616
4861
3706
3797
3723
3670
3738
3749
3778
3810
3786
3821
3792
3766
3775
3788
3751
3397
3813
3823
3697
3831
3836
3843
4850
4851
6386
3551
7474
3714
7480
3579
7473
3552
3445
3562
7491
3598
3574
7551
3576
3648
4876
7558
3573
7502
3512
3362
3498
3485
3493
4897
3761
4898
3563
3443
3613
4907
3495
4912
4917
3736
3734
3492
7547
7574
4942
6382
6385
3623
3395
6389
6394
3476
3477
6398
7464
3674
3599
3568
7475
7477
3610
3378
4924
3619
3523
4950
3676
7510
3581
3372
3460
4916
6391
3399
3621
3874
7601
7604
4023
4126
4172
6400
6402
6405
6406
6407
6410
3968
6416
6417
6419
6423
6426
4118
6435
6449
4076
6475
6482
6489
6490
6491
4050
4159
4069
6508
4200
4110
4203
6443
7595
3901
4010
3948
6418
6459
4024
4099
3940
6445
4178
4026
7660
4058
3987
4232
4233
4234
4339
4512
4212
4494
4610
4515
4583
4537
4547
4616
4625
4631
4719
6610
6522
7694
6527
6578
6559
6633
6545
7686
6536
6615
7704
6623
7713
6637
7720
5762
7095
5763
5764
5771
7134
5775
5777
7155
7076
5780
5794
5804
6982
5807
5808
6966
5815
5823
5824
5825
5831
5832
5843
6981
5844
5849
5855
5857
5860
5885
5889
6992
5891
5901
5854
5906
5167
5912
5913
5916
5933
5942
5069
6954
6955
5089
6958
5119
5116
6968
6969
5068
6971
6972
6974
6975
6977
6978
6980
6986
5947
5866
5918
6997
5894
5793
7020
5816
7030
7032
5878
7038
7049
7055
5209
7068
7069
5784
7072
7074
7078
7079
7090
7091
7093
7098
5853
7106
7107
5814
5768
7111
7113
5810
7119
7082
7123
5246
5915
7138
5863
7145
5837
5259
5195
7161
5862
7167
7171
5110
5652
6871
5658
6738
5665
6821
5676
5720
5423
5734
5742
5743
5753
5388
6715
6716
5746
6723
6725
6728
6729
6733
6746
6750
5662
5737
6775
5450
6779
6790
6791
6800
6804
6805
6809
5685
6825
6826
5669
6836
6864
6874
6875
5663
5670
5324
6904
6911
5701
5698
6927
6931
5749
6937
6677
7737

In [117]:
ls[0]

{204, 296}

In [124]:
data_df.loc[7288]

City                                                            Đà Lạt
Hotel name                                     Khách sạn Lacami Đà Lạt
Url                  https://mytour.vn/khach-san/29603-khach-san-la...
Address              36/6 Lê Văn Tám, Phường 10, Lê Văn Tám, Thành ...
Stars                                                              2.0
Price                                                           448088
Rating                                                             9.0
Number of reviews                                                   71
Reviews              ['Phòng tiện nghi đầy đủ\nLà nơi Tôi chọn để n...
Facilities           ['Bãi đỗ xe', 'Cho thuê xe máy', 'Đưa/đón khác...
Description          ['Với vẻ đẹp sang trọng và ấm cúng cùng nội th...
Nearby places        [('Cây Đa Quán 2', '294 m'), ('Sitooterie - Co...
Image                ['https://img.tripi.vn/cdn-cgi/image/width=840...
new_name                                                   lacamidalat
new_add                                  36/6levantam10levantamlamdong
Name: 7288, dtype: object

In [126]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7061 entries, 0 to 7744
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7061 non-null   object
 1   Hotel name         7061 non-null   object
 2   Url                7061 non-null   object
 3   Address            7061 non-null   object
 4   Stars              7061 non-null   float64
 5   Price              7061 non-null   int64
 6   Rating             7061 non-null   float64
 7   Number of reviews  7061 non-null   int64
 8   Reviews            7061 non-null   object
 9   Facilities         7061 non-null   object
 10  Description        6294 non-null   object
 11  Nearby places      7061 non-null   object
 12  Image              7061 non-null   object
 13  new_name           7061 non-null   object
 14  new_add            7061 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 882.6+ KB

In [128]:
data_df

,City,Hotel name,Url,Address,Stars,Price,Rating,Number of reviews,Reviews,Facilities,Description,Nearby places,Image,new_name,new_add
0,Hà Nội,Khách sạn HANZ Regal Hotel Hanoi,https://www.booking.com/hotel/vn/90-pham-huy-t...,"90 Pham Huy Thong, Quận Ba Đình, Hà Nội, Viê...",2.0,421890,7.8,86,"['“máy lạnh mát, wifi trong từng phòng nên mạn...","['Xe đưa đón sân bay', 'Wi-Fi miễn phí', 'P...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Hồ Ngọc Khánh', '0,3 km'), ('Trung tâm thươ...",['https://cf.bstatic.com/xdata/images/hotel/ma...,hanzregalhanoi,90phamhuythongbadinhhanoivietnam
1,Hà Nội,Khách sạn La Nueva Boutique Hotel Hanoi & Spa,https://www.booking.com/hotel/vn/hanoi-eleganc...,"32 Lo Su Street, Quận Hoàn Kiếm, Hà Nội, Viê...",4.0,1316000,9.3,209,"['“Địa điểm tuyệt vời, đi một xíu là ra đến hồ...","['Xe đưa đón sân bay', 'Phòng không hút thu...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Nhà hát múa rối Thăng Long', '0,1 km'), ('Đ...",['https://cf.bstatic.com/xdata/images/hotel/ma...,lanuevaboutiquehanoi,32losuhoankiemhanoivietnam
2,Hà Nội,Khách sạn La Storia Ruby Hotel,https://www.booking.com/hotel/vn/hanoi-eleganc...,"3 Yen Thai Street, Quận Hoàn Kiếm, Hà Nội, V...",3.0,625000,9.6,217,['“- vị trí gần hồ gươm rất tiện cho việc đi b...,"['Xe đưa đón sân bay', 'Phòng không hút thu...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Quảng Trường Đông Kinh Nghĩa Thục', '0,4 km...",['https://cf.bstatic.com/xdata/images/hotel/ma...,lastoriaruby,3yenthaihoankiemhanoivietnam
3,Hà Nội,Khách sạn LeaH Silk Hotel,https://www.booking.com/hotel/vn/leah-silk.vi....,"41- 43 Hàng Bông, Hoàn Kiếm , Hà Nội, Quận Hoà...",4.0,1800000,9.1,72,"['“Mình ở phòng có cửa thông với phòng khác, v...","['1 hồ bơi', 'Xe đưa đón sân bay', 'Phòng kh...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Nhà thờ Thánh Joseph', '0,3 km'), ('Quảng T...",['https://cf.bstatic.com/xdata/images/hotel/ma...,leahsilk,41-43hangbonghoankiemhoankiemhanoivietnam
4,Hà Nội,Khách sạn Babylon Premium Hotel & Spa,https://www.booking.com/hotel/vn/babylon-premi...,"05-07 Hàng Hòm, Quận Hoàn Kiếm, Hà Nội, Việ...",4.0,1262250,9.4,627,['“Phòng rất rộng và sạch.\nVị trí ngay giữa k...,"['Xe đưa đón sân bay', 'Phòng không hút thu...",\r\nBạn đủ điều kiện nhận giảm giá Genius tại ...,"[('Quảng Trường Đông Kinh Nghĩa Thục', '0,3 km...",['https://cf.bstatic.com/xdata/images/hotel/ma...,babylonpremium,05-07hanghomhoankiemhanoivietnam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7740,Hạ Long,Khách sạn The Twin,https://mytour.vn/khach-san/44177-khach-san-th...,"Tt 31-32 , Đường Hạ Long - Sun Premier Village...",4.0,1684766,8.0,1,['Giải quyết linh động tinh huống cho khách kh...,"['Đưa/đón khách sân bay', 'Lễ tân 24h', 'Giữ h...","['Tọa lạc ở thành phố Hạ Long, cách cáp treo N...","[('Nhà hàng Bayview', '369 m'), ('Nhà Hàng Phư...",['https://img.tripi.vn/cdn-cgi/image/width=124...,thetwin,tt31-32-sunpremiervillagehalong
7741,Hạ Long,Khách sạn Sea Star,https://mytour.vn/khach-san/39745-khach-san-se...,"Bt 08 - Khu Villa Sao Biển, Phan Chu Trinh, Th...",3.0,665456,8.2,9,['Tạm được\nĐi gia đình đúng dịp dịch nên cả n...,"['American Express', 'Đưa/đón khách sân bay', ...","['Được nâng cấp vào năm , Khách sạn Sea Stars ...","[('Nhà hàng Cua Vàng', '59 m'), ('1900 Coff...",['https://img.tripi.vn/cdn-cgi/image/width=124...,seastar,bt08-villasaobienphanchutrinh
7742,Hạ Long,Khách Sạn Dragon Hạ Long,https://mytour.vn/khach-san/53773-khach-san-dr...,"8 , Lộc Vừng 2 , Khu Premier Village , Đườn...",3.0,897838,8.4,0,[],"['Bãi đỗ xe', 'Cho thuê xe máy', 'Giữ hành lý'...",['Khách Sạn Dragon Hạ Long là nơi cung cấp dị...,[],['https://img.tripi.vn/cdn-cgi/image/width=124...,khachsandragonhalong,8cvung2premiervillageduonghalong
7743,Hạ Long,Khách Sạn Sunshine,https://mytour.vn/khach-san/49166-khach-san-su...,"56a Tuệ Tĩnh, Khu Đô Thị Hồng Vận, Đường Tuệ T...",2.0,508093,7.0,0,[],"['Lễ tân 24h', 'Giữ hành lý', 'Bán tour', 'Int...",['Sunshine Hotel in Móng Cái has 2-star accomm...,"[('Don Chicken Vincom Móng Cái', '930 m'), ('N...",['https://img.tripi.vn/cdn-cgi/image/width=124...,sunshine,56atuetinhhongvantuetinhmongcai
7744,Hạ Long,Khách sạn Galaxy Hạ Long,https://mytour.vn/khach-san/39775-khach-san-ga...,"15, Tiên Ông, Phường Bãi Cháy, Thành Phố Hạ Lo...",4.0,753251,9.4,5,['Galaxy Hotel Hạ Long\nMình đặt 1 phòng 3 giư...,"['Đưa/đón khách sân bay', 'Phòng gym', 'Giữ hà...",['Được UNESCO công nhận là di sản thiên nhiên ...,"[('Nhà Hàng Lâm Hải', '131 m'), ('Mixue Bãi Ch...",['https://img.tripi.vn/cdn-cgi/image/width=840...,galaxyhalong,15tienongchay

In [130]:
data_df.to_csv('data_maped.csv', index=False, encoding='utf8')

In [131]:
data_maped = pd.read_csv("data_maped.csv")

In [132]:
data_maped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7061 entries, 0 to 7060
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7061 non-null   object
 1   Hotel name         7061 non-null   object
 2   Url                7061 non-null   object
 3   Address            7061 non-null   object
 4   Stars              7061 non-null   float64
 5   Price              7061 non-null   int64
 6   Rating             7061 non-null   float64
 7   Number of reviews  7061 non-null   int64
 8   Reviews            7061 non-null   object
 9   Facilities         7061 non-null   object
 10  Description        6294 non-null   object
 11  Nearby places      7061 non-null   object
 12  Image              7061 non-null   object
 13  new_name           7055 non-null   object
 14  new_add            7058 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 827.6+ KB